---
- name: Set up Apache reverse proxy with Let's Encrypt SSL
  hosts: localhost
  become: yes
  connection: local
  vars:
    domain_name: "{{ domain_name }}"
    webroot_path: "/var/www/{{ domain_name }}"
    temp_config: "/etc/apache2/sites-available/{{ domain_name }}.conf"
    
  tasks:
    - name: Ensure webroot directory exists
      file:
        path: "{{ webroot_path }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy Editor File 
      template:
        src: editor.php
        dest: "{{ webroot_path }}/editor.php"

    - name: Copy Editor Config File 
      template:
        src: editor.config.php
        dest: "{{ webroot_path }}/editor.config.php"

    - name: Obtain Let's Encrypt SSL certificate
      command: >
        certbot certonly --webroot -w {{ webroot_path }} -n --agree-tos --email admin@{{ domain_name }} -d {{ domain_name }}
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
        
    - name: Create final Apache virtual host configuration (with SSL)
      template:
        src: add_site.conf.j2
        dest: "{{ temp_config }}"
      notify:
        - reload apache
        
  handlers:
      - name: reload apache
        service:
          name: apache2
          state: reloaded
