---
- name: Install MySQL on Ubuntu 22.04
  hosts: localhost
  become: yes
  connection: local
  vars:
    mysql_root_password: "{{ mysql_root_password }}"
  tasks:
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Ensure MySQL service is started and enabled
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL for Python 3
      pip:
        name: PyMySQL
        executable: pip3

    - name: Set MySQL root password and authentication method
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: yes
        priv: '*.*:ALL,GRANT'
        plugin: mysql_native_password

    - name: Remove anonymous MySQL users
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Remove the test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Reload MySQL privilege tables
      mysql_db:
        name: "*"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
